#pragma once

// (GLフォーマット型, 保存する時のType, 1画素に使うType数, BaseFormatにする場合の型)
#define SEQ_FORMATLIST \
	((GL_R8, GL_UNSIGNED_BYTE, 1, GL_RED)) \
	((GL_R8_SNORM, GL_BYTE, 1, GL_RED)) \
	((GL_R16, GL_UNSIGNED_SHORT, 1, GL_RED)) \
	((GL_R16_SNORM, GL_SHORT, 1, GL_RED)) \
	((GL_RG8, GL_UNSIGNED_BYTE, 2, GL_RG)) \
	((GL_RG8_SNORM, GL_BYTE, 2, GL_RG)) \
	((GL_RG16, GL_UNSIGNED_SHORT, 2, GL_RG)) \
	((GL_RG16_SNORM, GL_SHORT, 2, GL_RG)) \
	((GL_R3_G3_B2, GL_UNSIGNED_BYTE_3_3_2, 1, GL_RGB)) \
	((GL_RGB4, GL_UNSIGNED_SHORT_4_4_4_4, 1, GL_RGB)) \
	((GL_RGB5, GL_UNSIGNED_SHORT_5_5_5_1, 1, GL_RGB)) \
	((GL_RGB8, GL_UNSIGNED_BYTE, 3, GL_RGB)) \
	((GL_RGB8_SNORM, GL_BYTE, 3, GL_RGB)) \
	((GL_RGB10, GL_UNSIGNED_INT_10_10_10_2, 1, GL_RGB)) \
	((GL_RGB12, GL_UNSIGNED_BYTE, 3, GL_RGB)) \
	((GL_RGB16_SNORM, GL_SHORT, 3, GL_RGB)) \
	((GL_RGBA2, GL_UNSIGNED_SHORT_4_4_4_4, 1, GL_RGBA)) \
	((GL_RGBA4, GL_UNSIGNED_SHORT_4_4_4_4, 1, GL_RGBA)) \
	((GL_RGB5_A1, GL_UNSIGNED_SHORT_5_5_5_1, 1, GL_RGBA)) \
	((GL_RGBA8, GL_UNSIGNED_BYTE, 4, GL_RGBA)) \
	((GL_RGBA8_SNORM, GL_BYTE, 4, GL_RGBA)) \
	((GL_RGB10_A2, GL_UNSIGNED_INT_10_10_10_2, 1, GL_RGBA)) \
	((GL_RGB10_A2UI, GL_UNSIGNED_INT_10_10_10_2, 1, GL_RGBA)) \
	((GL_RGBA12, GL_UNSIGNED_SHORT, 4, GL_RGBA)) \
	((GL_RGBA16, GL_UNSIGNED_SHORT, 4, GL_RGBA)) \
	((GL_SRGB8, GL_UNSIGNED_BYTE, 3, GL_RGB)) \
	((GL_SRGB8_ALPHA8, GL_UNSIGNED_BYTE, 4, GL_RGBA)) \
	((GL_R16F, GL_HALF_FLOAT, 1, GL_RED)) \
	((GL_RG16F, GL_HALF_FLOAT, 2, GL_RG)) \
	((GL_RGB16F, GL_HALF_FLOAT, 3, GL_RGB)) \
	((GL_RGBA16F, GL_HALF_FLOAT, 4, GL_RGBA)) \
	((GL_R32F, GL_FLOAT, 1, GL_RED)) \
	((GL_RG32F, GL_FLOAT, 2, GL_RG)) \
	((GL_RGB32F, GL_FLOAT, 3, GL_RGB)) \
	((GL_RGBA32F, GL_FLOAT, 4, GL_RGBA)) \
	((GL_R11F_G11F_B10F, GL_HALF_FLOAT, 3, GL_RGB)) \
	((GL_RGB9_E5, GL_UNSIGNED_INT_5_9_9_9_REV, 1, GL_RGB)) \
	((GL_R8I, GL_BYTE, 1, GL_RED)) \
	((GL_R8UI, GL_UNSIGNED_BYTE, 1, GL_RED)) \
	((GL_R16I, GL_SHORT, 1, GL_RED)) \
	((GL_R16UI, GL_UNSIGNED_SHORT, 1, GL_RED)) \
	((GL_R32I, GL_INT, 1, GL_RED)) \
	((GL_R32UI, GL_UNSIGNED_INT, 1, GL_RED)) \
	((GL_RG8I, GL_BYTE, 2, GL_RG)) \
	((GL_RG8UI, GL_UNSIGNED_BYTE, 2, GL_RG)) \
	((GL_RG16I, GL_SHORT, 2, GL_RG)) \
	((GL_RG16UI, GL_UNSIGNED_SHORT, 2, GL_RG)) \
	((GL_RG32I, GL_INT, 2, GL_RG)) \
	((GL_RG32UI, GL_UNSIGNED_INT, 2, GL_RG)) \
	((GL_RGB8I, GL_BYTE, 3, GL_RGB)) \
	((GL_RGB8UI, GL_UNSIGNED_BYTE, 3, GL_RGB)) \
	((GL_RGB16I, GL_SHORT, 3, GL_RGB)) \
	((GL_RGB16UI, GL_UNSIGNED_SHORT, 3, GL_RGB)) \
	((GL_RGB32I, GL_INT, 3, GL_RGB)) \
	((GL_RGB32UI, GL_UNSIGNED_INT, 3, GL_RGB)) \
	((GL_RGBA8I, GL_BYTE, 4, GL_RGBA)) \
	((GL_RGBA8UI, GL_UNSIGNED_BYTE, 4, GL_RGBA)) \
	((GL_RGBA16I, GL_SHORT, 4, GL_RGBA)) \
	((GL_RGBA16UI, GL_UNSIGNED_SHORT, 4, GL_RGBA)) \
	((GL_RGBA32I, GL_INT, 4, GL_RGBA)) \
	((GL_RGBA32UI, GL_UNSIGNED_INT, 4, GL_RGBA)) \
	((GL_DEPTH_COMPONENT16, GL_UNSIGNED_SHORT, 1, GL_DEPTH_COMPONENT)) \
	((GL_DEPTH_COMPONENT24, GL_UNSIGNED_INT, 1, GL_DEPTH_COMPONENT)) \
	((GL_DEPTH_COMPONENT32, GL_UNSIGNED_INT, 1, GL_DEPTH_COMPONENT)) \
	((GL_DEPTH_COMPONENT32F, GL_FLOAT, 1, GL_DEPTH_COMPONENT)) \
	((GL_STENCIL_INDEX4, GL_UNSIGNED_BYTE, 1, GL_STENCIL_INDEX)) \
	((GL_STENCIL_INDEX8, GL_UNSIGNED_BYTE, 1, GL_STENCIL_INDEX)) \
	((GL_STENCIL_INDEX16, GL_UNSIGNED_SHORT, 1, GL_STENCIL_INDEX)) \
	((GL_DEPTH24_STENCIL8, GL_FLOAT_32_UNSIGNED_INT_24_8_REV, 1, GL_DEPTH_STENCIL))

// (Typeフラグ, 要素のバイトサイズ)
#define SEQ_TYPELIST \
	((GL_UNSIGNED_BYTE, GLubyte)) \
	((GL_BYTE, GLbyte)) \
	((GL_UNSIGNED_SHORT, GLushort)) \
	((GL_SHORT, GLshort)) \
	((GL_UNSIGNED_INT, GLuint)) \
	((GL_INT, GLint)) \
	((GL_HALF_FLOAT, GLshort)) \
	((GL_FLOAT, GLfloat)) \
	((GL_UNSIGNED_BYTE_3_3_2, GLubyte)) \
	((GL_UNSIGNED_BYTE_2_3_3_REV, GLubyte)) \
	((GL_UNSIGNED_SHORT_5_6_5, GLushort)) \
	((GL_UNSIGNED_SHORT_5_6_5_REV, GLushort)) \
	((GL_UNSIGNED_SHORT_4_4_4_4, GLushort)) \
	((GL_UNSIGNED_SHORT_4_4_4_4_REV, GLushort)) \
	((GL_UNSIGNED_SHORT_5_5_5_1, GLushort)) \
	((GL_UNSIGNED_SHORT_1_5_5_5_REV, GLushort)) \
	((GL_UNSIGNED_INT_8_8_8_8, GLuint)) \
	((GL_UNSIGNED_INT_8_8_8_8_REV, GLuint)) \
	((GL_UNSIGNED_INT_10_10_10_2, GLuint)) \
	((GL_UNSIGNED_INT_2_10_10_10_REV, GLuint)) \
	((GL_UNSIGNED_INT_24_8, GLuint)) \
	((GL_UNSIGNED_INT_10F_11F_11F_REV, GLuint)) \
	((GL_UNSIGNED_INT_5_9_9_9_REV, GLuint)) \
	((GL_FLOAT_32_UNSIGNED_INT_24_8_REV, GLuint))
